# Configuration of Pre-commit Hooks. For more information, see https://pre-commit.com.
repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.8.0
    hooks:
      - id: pre-commit-update # Autoupdate pre-commit hooks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict # Check for files with names that differ only in case.
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer # Ensure files end with a newline.
      - id: mixed-line-ending
      - id: no-commit-to-branch # Prevent commits to main and master branches.
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext", "md"] # Preserve Markdown hard line breaks.

  - repo: https://github.com/gitleaks/gitleaks # Detect secrets in commits.
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat # Format Markdown files.
        additional_dependencies:
          - mdformat-gfm # Support GitHub Flavored Markdown.
          - mdformat-ruff # Support Python code blocks linted with Ruff.
          - mdformat-tables # Support GitHub style tables.

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/astral-sh/ruff-pre-commit # Lint and format Python code with Ruff.
    rev: v0.12.9
    hooks:
      - id: ruff-check
        args: ["--fix", "--ignore", "FIX002"] # Allow TODO comments in commits.
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit # Update the uv lockfile.
    rev: 0.8.10
    hooks:
      - id: uv-lock

  - repo: https://github.com/RobertCraigie/pyright-python # Check typing with Pyright.
    rev: v1.1.403
    hooks:
      - id: pyright
