"""Private backend<->plugin transport contracts for the RPi camera seam."""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, HttpUrl, WebsocketUrl

# These bounds mirror existing seam contracts: pairing codes are 6-character
# operator codes, and key IDs/camera IDs are URL-safe opaque IDs.
_PAIRING_CODE_PATTERN = r"^[A-Z0-9]{6}$"
_SAFE_IDENTIFIER_PATTERN = r"^[A-Za-z0-9._~-]+$"

# Pydantic validates absolute HTTP/WebSocket URLs. Upload acks also accept
# backend-rooted relative URLs, so that seam still needs a small local rule.
_HTTP_OR_RELATIVE_URL_PATTERN = r"^(https?://[^\s]+|/([^\s/][^\s]*)?)$"

_PairingCode = Annotated[str, Field(min_length=6, max_length=6, pattern=_PAIRING_CODE_PATTERN)]
_DeviceFingerprint = Annotated[str, Field(min_length=8, max_length=64)]
_SafeIdentifier = Annotated[str, Field(min_length=1, max_length=128, pattern=_SAFE_IDENTIFIER_PATTERN)]
_GeneratedKeyId = Annotated[str, Field(min_length=8, max_length=64, pattern=_SAFE_IDENTIFIER_PATTERN)]
_BootstrapKeyId = Annotated[str, Field(min_length=1, max_length=64, pattern=_SAFE_IDENTIFIER_PATTERN)]
_HttpOrRelativeUrl = Annotated[str, Field(min_length=1, max_length=2048, pattern=_HTTP_OR_RELATIVE_URL_PATTERN)]
_RelayMessageId = Annotated[str, Field(min_length=1, max_length=64, pattern=_SAFE_IDENTIFIER_PATTERN)]


class RelayAuthScheme(StrEnum):
    """Authentication schemes understood by the device seam."""

    DEVICE_ASSERTION = "device_assertion"


class DevicePublicKeyJWK(BaseModel):
    """Public P-256 JWK registered by the Pi during pairing."""

    kty: str = Field(pattern="^EC$")
    crv: str = Field(pattern="^P-256$")
    x: str = Field(min_length=1)
    y: str = Field(min_length=1)
    use: str | None = None
    kid: str | None = None

    model_config = ConfigDict(extra="forbid")


class PairingRegisterRequest(BaseModel):
    """Pi -> backend pairing registration payload."""

    code: _PairingCode = Field(
        description="6-character uppercase alphanumeric pairing code generated by the Pi.",
    )
    rpi_fingerprint: _DeviceFingerprint = Field(
        description="Random nonce generated by the Pi. Required to retrieve credentials later.",
    )
    public_key_jwk: DevicePublicKeyJWK = Field(description="Public P-256 JWK generated by the Pi.")
    key_id: _GeneratedKeyId


class PairingRegisterResponse(BaseModel):
    """Backend -> Pi acknowledgement of a pairing registration."""

    code: _PairingCode
    expires_in: int = Field(gt=0, le=600, description="Seconds until the pairing code expires.")


class PairingStatus(StrEnum):
    """Observable pairing states exchanged at the device seam."""

    WAITING = "waiting"
    PAIRED = "paired"


class PairingClaimedBootstrap(BaseModel):
    """Backend -> Pi relay bootstrap payload returned once pairing completes."""

    camera_id: _SafeIdentifier
    ws_url: WebsocketUrl
    auth_scheme: RelayAuthScheme
    key_id: _BootstrapKeyId


class PairingPollResponse(BaseModel):
    """Backend -> Pi current pairing state."""

    status: Literal[PairingStatus.WAITING, PairingStatus.PAIRED]
    camera_id: _SafeIdentifier | None = None
    ws_url: WebsocketUrl | None = None
    auth_scheme: RelayAuthScheme | None = None
    key_id: _BootstrapKeyId | None = None

    @classmethod
    def waiting(cls) -> PairingPollResponse:
        """Build the standard waiting response."""
        return cls(status=PairingStatus.WAITING)

    @classmethod
    def from_claimed_bootstrap(cls, payload: PairingClaimedBootstrap) -> PairingPollResponse:
        """Build the paired poll response from the claimed bootstrap payload."""
        return cls(status=PairingStatus.PAIRED, **payload.model_dump())


class PairingPendingRecord(BaseModel):
    """Redis-stored pairing record before a user claims the code."""

    status: Literal[PairingStatus.WAITING] = PairingStatus.WAITING
    rpi_fingerprint: _DeviceFingerprint
    public_key_jwk: DevicePublicKeyJWK
    key_id: _GeneratedKeyId


class PairingClaimedRecord(PairingClaimedBootstrap):
    """Redis-stored pairing record after the backend claims the code."""

    status: Literal[PairingStatus.PAIRED] = PairingStatus.PAIRED
    rpi_fingerprint: _DeviceFingerprint


class LocalAccessInfo(BaseModel):
    """Plugin -> backend -> frontend local direct-connection bootstrap payload."""

    local_api_key: Annotated[str, Field(min_length=8, max_length=256)]
    candidate_urls: list[HttpUrl] = Field(min_length=1, max_length=16)
    mdns_name: Annotated[str, Field(max_length=253, pattern=r"^[A-Za-z0-9.-]+$")] | None = None


class DeviceImageUploadAck(BaseModel):
    """Backend -> Pi acknowledgement of a direct image upload."""

    image_id: _SafeIdentifier = Field(description="Stored backend image ID.")
    image_url: _HttpOrRelativeUrl = Field(description="Backend-hosted URL for the stored image")


class DevicePreviewThumbnailAck(BaseModel):
    """Backend -> Pi acknowledgement of a cached preview-thumbnail upload."""

    preview_thumbnail_url: _HttpOrRelativeUrl = Field(description="Backend-hosted URL for the cached preview thumbnail")


class RelayMessageType(StrEnum):
    """Message types used by the HTTP-over-WebSocket relay."""

    REQUEST = "request"
    RESPONSE = "response"
    PING = "ping"
    PONG = "pong"


SAFE_RELAY_TRACE_HEADERS: frozenset[str] = frozenset({"traceparent", "tracestate", "baggage"})
"""Header names allowed to cross the relay boundary."""

RELAY_WS_TEXT_FRAME_LIMIT_BYTES = 64 * 1024
"""Maximum JSON/text relay frame size shared by the backend and Pi."""


class RelayCommandEnvelope(BaseModel):
    """Backend -> Pi HTTP-like relay command."""

    id: _RelayMessageId
    type: Literal[RelayMessageType.REQUEST] = RelayMessageType.REQUEST
    method: Annotated[str, Field(min_length=1, max_length=16)]
    path: Annotated[str, Field(min_length=1, max_length=2048)]
    params: dict[str, Any] = Field(default_factory=dict)
    body: dict[str, Any] | None = None
    headers: dict[str, str] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")


class RelayResponseEnvelope(BaseModel):
    """Pi -> backend relay response header payload."""

    id: _RelayMessageId
    type: Literal[RelayMessageType.RESPONSE] = RelayMessageType.RESPONSE
    status: int = Field(ge=100, le=599)
    content_type: Annotated[str, Field(min_length=1, max_length=255)] | None = None
    has_binary: bool = False
    data: dict[str, Any] | list[Any] | str | None = None

    model_config = ConfigDict(extra="forbid")
