"""Private backend<->plugin transport contracts for the RPi camera seam."""

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class RelayAuthScheme(StrEnum):
    """Authentication schemes understood by the device seam."""

    DEVICE_ASSERTION = "device_assertion"


class DevicePublicKeyJWK(BaseModel):
    """Public P-256 JWK registered by the Pi during pairing."""

    kty: str = Field(pattern="^EC$")
    crv: str = Field(pattern="^P-256$")
    x: str = Field(min_length=1)
    y: str = Field(min_length=1)
    use: str | None = None
    kid: str | None = None

    model_config = ConfigDict(extra="forbid")


class PairingRegisterRequest(BaseModel):
    """Pi -> backend pairing registration payload."""

    code: str = Field(
        min_length=6,
        max_length=6,
        pattern=r"^[A-Z0-9]{6}$",
        description="6-character uppercase alphanumeric pairing code generated by the Pi.",
    )
    rpi_fingerprint: str = Field(
        min_length=8,
        max_length=64,
        description="Random nonce generated by the Pi. Required to retrieve credentials later.",
    )
    public_key_jwk: DevicePublicKeyJWK = Field(description="Public P-256 JWK generated by the Pi.")
    key_id: str = Field(min_length=8, max_length=64, pattern=r"^[A-Za-z0-9._~-]+$")


class PairingRegisterResponse(BaseModel):
    """Backend -> Pi acknowledgement of a pairing registration."""

    code: str
    expires_in: int = Field(description="Seconds until the pairing code expires.")


class PairingStatus(StrEnum):
    """Observable pairing states exchanged at the device seam."""

    WAITING = "waiting"
    PAIRED = "paired"


class PairingClaimedBootstrap(BaseModel):
    """Backend -> Pi relay bootstrap payload returned once pairing completes."""

    camera_id: str
    ws_url: str
    auth_scheme: RelayAuthScheme
    key_id: str


class PairingPollResponse(BaseModel):
    """Backend -> Pi current pairing state."""

    status: Literal[PairingStatus.WAITING, PairingStatus.PAIRED]
    camera_id: str | None = None
    ws_url: str | None = None
    auth_scheme: RelayAuthScheme | None = None
    key_id: str | None = None

    @classmethod
    def waiting(cls) -> PairingPollResponse:
        """Build the standard waiting response."""
        return cls(status=PairingStatus.WAITING)

    @classmethod
    def from_claimed_bootstrap(cls, payload: PairingClaimedBootstrap) -> PairingPollResponse:
        """Build the paired poll response from the claimed bootstrap payload."""
        return cls(status=PairingStatus.PAIRED, **payload.model_dump())


class PairingPendingRecord(BaseModel):
    """Redis-stored pairing record before a user claims the code."""

    status: Literal[PairingStatus.WAITING] = PairingStatus.WAITING
    rpi_fingerprint: str = Field(min_length=8, max_length=64)
    public_key_jwk: DevicePublicKeyJWK
    key_id: str = Field(min_length=8, max_length=64, pattern=r"^[A-Za-z0-9._~-]+$")


class PairingClaimedRecord(PairingClaimedBootstrap):
    """Redis-stored pairing record after the backend claims the code."""

    status: Literal[PairingStatus.PAIRED] = PairingStatus.PAIRED


class LocalAccessInfo(BaseModel):
    """Plugin -> backend -> frontend local direct-connection bootstrap payload."""

    local_api_key: str
    candidate_urls: list[str]
    mdns_name: str | None


class DeviceImageUploadAck(BaseModel):
    """Backend -> Pi acknowledgement of a direct image upload."""

    image_id: str = Field(description="Stored image ID in hex32 (UUID without dashes)")
    image_url: str = Field(description="Backend-hosted URL for the stored image")


class DevicePreviewThumbnailAck(BaseModel):
    """Backend -> Pi acknowledgement of a cached preview-thumbnail upload."""

    preview_thumbnail_url: str = Field(description="Backend-hosted URL for the cached preview thumbnail")


class RelayMessageType(StrEnum):
    """Message types used by the HTTP-over-WebSocket relay."""

    REQUEST = "request"
    RESPONSE = "response"
    PING = "ping"
    PONG = "pong"


SAFE_RELAY_TRACE_HEADERS: frozenset[str] = frozenset({"traceparent", "tracestate", "baggage"})
"""Header names allowed to cross the relay boundary."""


class RelayCommandEnvelope(BaseModel):
    """Backend -> Pi HTTP-like relay command."""

    id: str
    type: Literal[RelayMessageType.REQUEST] = RelayMessageType.REQUEST
    method: str
    path: str
    params: dict[str, Any] = Field(default_factory=dict)
    body: dict[str, Any] | None = None
    headers: dict[str, str] = Field(default_factory=dict)


class RelayResponseEnvelope(BaseModel):
    """Pi -> backend relay response header payload."""

    id: str
    type: Literal[RelayMessageType.RESPONSE] = RelayMessageType.RESPONSE
    status: int
    content_type: str | None = None
    has_binary: bool = False
    data: dict[str, Any] | list[Any] | str | None = None
