"""Private backend<->plugin transport contracts for the RPi camera seam."""

from __future__ import annotations

from enum import StrEnum
from pathlib import PurePosixPath
from typing import Annotated, Any, Literal
from urllib.parse import unquote

from pydantic import BaseModel, ConfigDict, Field, FiniteFloat, HttpUrl, StrictBool, StrictInt, StrictStr, WebsocketUrl

PAIRING_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
PAIRING_CODE_LENGTH = 6
PAIRING_CODE_PATTERN = rf"^[{PAIRING_CODE_ALPHABET}]{{{PAIRING_CODE_LENGTH}}}$"

# These bounds mirror existing seam contracts: pairing codes are short
# operator codes without ambiguous 0/O/1/I characters, and key IDs/camera IDs
# are URL-safe opaque IDs.
_SAFE_IDENTIFIER_PATTERN = r"^[A-Za-z0-9._~-]+$"

# Pydantic validates absolute HTTP/WebSocket URLs. Upload acks also accept
# backend-rooted relative URLs, so that seam still needs a small local rule.
_HTTP_OR_RELATIVE_URL_PATTERN = r"^(https?://[^\s]+|/([^\s/][^\s]*)?)$"

PairingCode = Annotated[
    str,
    Field(
        min_length=PAIRING_CODE_LENGTH,
        max_length=PAIRING_CODE_LENGTH,
        pattern=PAIRING_CODE_PATTERN,
        description="6-character uppercase pairing code generated by the Pi.",
    ),
]
_DeviceFingerprint = Annotated[str, Field(min_length=8, max_length=64)]
_SafeIdentifier = Annotated[str, Field(min_length=1, max_length=128, pattern=_SAFE_IDENTIFIER_PATTERN)]
_GeneratedKeyId = Annotated[str, Field(min_length=8, max_length=64, pattern=_SAFE_IDENTIFIER_PATTERN)]
_BootstrapKeyId = Annotated[str, Field(min_length=1, max_length=64, pattern=_SAFE_IDENTIFIER_PATTERN)]
_HttpOrRelativeUrl = Annotated[str, Field(min_length=1, max_length=2048, pattern=_HTTP_OR_RELATIVE_URL_PATTERN)]
_RelayMessageId = Annotated[str, Field(min_length=1, max_length=64, pattern=_SAFE_IDENTIFIER_PATTERN)]
_RelayParamName = Annotated[StrictStr, Field(min_length=1, max_length=64, pattern=_SAFE_IDENTIFIER_PATTERN)]
_RelayParamValue = Annotated[StrictStr, Field(max_length=256)] | StrictInt | FiniteFloat | StrictBool
_RelayHeaderName = Annotated[StrictStr, Field(min_length=1, max_length=64, pattern=_SAFE_IDENTIFIER_PATTERN)]
_RelayHeaderValue = Annotated[StrictStr, Field(max_length=512)]
_PARENT_PATH_SEGMENT = ".."
_BINARY_MEDIA_TYPE_PREFIXES = ("image/", "video/")
_OCTET_STREAM_MEDIA_TYPE = "application/octet-stream"
_MAX_RELAY_PATH_UNQUOTE_PASSES = 4
_MAX_RELAY_QUERY_PARAMS = 16
_MAX_RELAY_HEADERS = 16


class RelayAuthScheme(StrEnum):
    """Authentication schemes understood by the device seam."""

    DEVICE_ASSERTION = "device_assertion"


class DevicePublicKeyJWK(BaseModel):
    """Public P-256 JWK registered by the Pi during pairing."""

    kty: str = Field(pattern="^EC$")
    crv: str = Field(pattern="^P-256$")
    x: str = Field(min_length=1)
    y: str = Field(min_length=1)
    use: str | None = None
    kid: str | None = None

    model_config = ConfigDict(extra="forbid")


class PairingRegisterRequest(BaseModel):
    """Pi -> backend pairing registration payload."""

    code: PairingCode
    rpi_fingerprint: _DeviceFingerprint = Field(
        description="Random nonce generated by the Pi. Required to retrieve credentials later.",
    )
    public_key_jwk: DevicePublicKeyJWK = Field(description="Public P-256 JWK generated by the Pi.")
    key_id: _GeneratedKeyId


class PairingRegisterResponse(BaseModel):
    """Backend -> Pi acknowledgement of a pairing registration."""

    code: PairingCode
    expires_in: int = Field(gt=0, le=600, description="Seconds until the pairing code expires.")


class PairingStatus(StrEnum):
    """Observable pairing states exchanged at the device seam."""

    WAITING = "waiting"
    PAIRED = "paired"


class PairingClaimedBootstrap(BaseModel):
    """Backend -> Pi relay bootstrap payload returned once pairing completes."""

    camera_id: _SafeIdentifier
    ws_url: WebsocketUrl
    auth_scheme: RelayAuthScheme
    key_id: _BootstrapKeyId


class PairingPollResponse(BaseModel):
    """Backend -> Pi current pairing state."""

    status: Literal[PairingStatus.WAITING, PairingStatus.PAIRED]
    camera_id: _SafeIdentifier | None = None
    ws_url: WebsocketUrl | None = None
    auth_scheme: RelayAuthScheme | None = None
    key_id: _BootstrapKeyId | None = None

    @classmethod
    def waiting(cls) -> PairingPollResponse:
        """Build the standard waiting response."""
        return cls(status=PairingStatus.WAITING)

    @classmethod
    def from_claimed_bootstrap(cls, payload: PairingClaimedBootstrap) -> PairingPollResponse:
        """Build the paired poll response from the claimed bootstrap payload."""
        return cls(status=PairingStatus.PAIRED, **payload.model_dump())


class PairingPendingRecord(BaseModel):
    """Redis-stored pairing record before a user claims the code."""

    status: Literal[PairingStatus.WAITING] = PairingStatus.WAITING
    rpi_fingerprint: _DeviceFingerprint
    public_key_jwk: DevicePublicKeyJWK
    key_id: _GeneratedKeyId


class PairingClaimedRecord(PairingClaimedBootstrap):
    """Redis-stored pairing record after the backend claims the code."""

    status: Literal[PairingStatus.PAIRED] = PairingStatus.PAIRED
    rpi_fingerprint: _DeviceFingerprint


class LocalAccessInfo(BaseModel):
    """Plugin -> backend -> frontend local direct-connection bootstrap payload."""

    local_api_key: Annotated[str, Field(min_length=8, max_length=256)]
    candidate_urls: list[HttpUrl] = Field(min_length=1, max_length=16)
    mdns_name: Annotated[str, Field(max_length=253, pattern=r"^[A-Za-z0-9.-]+$")] | None = None


class DeviceImageUploadAck(BaseModel):
    """Backend -> Pi acknowledgement of a direct image upload."""

    image_id: _SafeIdentifier = Field(description="Stored backend image ID.")
    image_url: _HttpOrRelativeUrl = Field(description="Backend-hosted URL for the stored image")


class DevicePreviewThumbnailAck(BaseModel):
    """Backend -> Pi acknowledgement of a cached preview-thumbnail upload."""

    preview_thumbnail_url: _HttpOrRelativeUrl = Field(description="Backend-hosted URL for the cached preview thumbnail")


class RelayMessageType(StrEnum):
    """Message types used by the HTTP-over-WebSocket relay."""

    REQUEST = "request"
    RESPONSE = "response"
    PING = "ping"
    PONG = "pong"


_SAFE_RELAY_TRACE_HEADERS: frozenset[str] = frozenset({"traceparent", "tracestate", "baggage"})
"""Header names allowed to cross the relay boundary."""

RELAY_WS_TEXT_FRAME_LIMIT_BYTES = 64 * 1024
"""Maximum JSON/text relay frame size shared by the backend and Pi."""

RELAY_COMMAND_TIMEOUT_SECONDS = 30.0
"""Pi-side deadline for dispatching one relayed command to its local API.

The backend's per-command wait must exceed this (plus grace) so the Pi's own
timeout response reaches the caller instead of a backend-side TimeoutError."""

RELAY_COMMAND_FORBIDDEN_DETAIL = "Relay command is not allowed."
"""Canonical detail returned when a relay command is outside the allowlist."""

RELAY_ALLOWED_EXACT_COMMANDS: frozenset[tuple[str, str]] = frozenset(
    {
        ("DELETE", "/pairing"),
        ("DELETE", "/streams/youtube"),
        ("GET", "/camera"),
        ("GET", "/camera/controls"),
        ("GET", "/streams/youtube"),
        ("GET", "/system/local-access"),
        ("GET", "/system/telemetry"),
        ("PATCH", "/camera/controls"),
        ("POST", "/captures"),
        ("POST", "/preview/start"),
        ("POST", "/preview/stop"),
        ("POST", "/streams/youtube"),
        ("PUT", "/camera/focus"),
    }
)
"""Exact HTTP-like relay commands permitted across the backend<->Pi seam."""

RELAY_ALLOWED_PREFIX_COMMANDS: frozenset[tuple[str, str]] = frozenset({("GET", "/preview/hls/")})
"""Prefix-based relay commands. Prefixes must end in '/' to avoid sibling matches."""


class RelayCommandEnvelope(BaseModel):
    """Backend -> Pi HTTP-like relay command."""

    id: _RelayMessageId
    type: Literal[RelayMessageType.REQUEST] = RelayMessageType.REQUEST
    method: Annotated[str, Field(min_length=1, max_length=16)]
    path: Annotated[str, Field(min_length=1, max_length=2048)]
    params: dict[_RelayParamName, _RelayParamValue] = Field(default_factory=dict, max_length=_MAX_RELAY_QUERY_PARAMS)
    body: dict[str, Any] | None = None
    headers: dict[_RelayHeaderName, _RelayHeaderValue] = Field(default_factory=dict, max_length=_MAX_RELAY_HEADERS)

    model_config = ConfigDict(extra="forbid")


class RelayResponseEnvelope(BaseModel):
    """Pi -> backend relay response header payload."""

    id: _RelayMessageId
    type: Literal[RelayMessageType.RESPONSE] = RelayMessageType.RESPONSE
    status: int = Field(ge=100, le=599)
    content_type: Annotated[str, Field(min_length=1, max_length=255)] | None = None
    has_binary: bool = False
    data: dict[str, Any] | list[Any] | str | None = None

    model_config = ConfigDict(extra="forbid")


def _normalize_relay_path(path: str) -> str | None:
    """Return the canonical relay path, or None when the path is not absolute."""
    decoded_path = path
    for _ in range(_MAX_RELAY_PATH_UNQUOTE_PASSES):
        next_path = unquote(decoded_path)
        if next_path == decoded_path:
            break
        decoded_path = next_path
    else:
        if unquote(decoded_path) != decoded_path:
            return None
    if not decoded_path.startswith("/"):
        return None
    if _PARENT_PATH_SEGMENT in PurePosixPath(decoded_path).parts:
        return None
    return decoded_path.rstrip("/") or "/"


def relay_command_is_allowed(method: str, path: str) -> bool:
    """Return whether a backend relay command may reach the Pi's local API."""
    normalized_path = _normalize_relay_path(path)
    if normalized_path is None:
        return False

    method = method.upper()
    if (method, normalized_path) in RELAY_ALLOWED_EXACT_COMMANDS:
        return True

    return any(
        method == allowed_method and normalized_path.startswith(prefix)
        for allowed_method, prefix in RELAY_ALLOWED_PREFIX_COMMANDS
    )


def extract_safe_relay_headers(headers: object) -> dict[str, str]:
    """Return relay-safe tracing headers from an untrusted header mapping."""
    if not isinstance(headers, dict):
        return {}

    safe_headers: dict[str, str] = {}
    for name, value in headers.items():
        if not isinstance(name, str) or not isinstance(value, str):
            continue
        normalized_name = name.lower()
        if normalized_name in _SAFE_RELAY_TRACE_HEADERS:
            safe_headers[normalized_name] = value
    return safe_headers


def relay_content_type_is_binary(content_type: str | None) -> bool:
    """Return whether an HTTP response body should travel as a binary frame."""
    if not content_type:
        return False
    media_type = content_type.split(";", 1)[0].strip().lower()
    return media_type.startswith(_BINARY_MEDIA_TYPE_PREFIXES) or media_type == _OCTET_STREAM_MEDIA_TYPE


def build_relay_command(
    msg_id: str,
    method: str,
    path: str,
    params: dict[str, Any] | None = None,
    body: dict[str, Any] | None = None,
    headers: object = None,
) -> RelayCommandEnvelope:
    """Build a backend->Pi relay command envelope."""
    return RelayCommandEnvelope(
        id=msg_id,
        method=method.upper(),
        path=path,
        params=params or {},
        body=body,
        headers=extract_safe_relay_headers(headers),
    )
