from PIL.Image import Image as PilImage

class Picamera2:
    camera_properties: dict[str, object]
    def __init__(self, camera_num: int = 0) -> None: ...
    def configure(self, config: object) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
    def capture_image(self) -> PilImage: ...
    def capture_metadata(self) -> dict[str, object] | None: ...
    def start_recording(self, encoder: object, output: object) -> None: ...
    def stop_recording(self) -> None: ...
    def create_still_configuration(self, **kwargs: object) -> dict[str, object]: ...
    def create_video_configuration(self, **kwargs: object) -> dict[str, object]: ...
